# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-webserver
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-test
  template:
    metadata:
      labels:
        app: nginx-test
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 8888
      #namespace: default
